---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-core-kyma-project-io-kyma-project-io-v1beta1-registrycacheconfig
  failurePolicy: Fail
  name: vregistrycacheconfig-v1beta1.kb.io
  rules:
  - apiGroups:
    - core.kyma-project.io.kyma-project.io
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - registrycacheconfigs
  sideEffects: None
