// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// DNSValidator is an autogenerated mock type for the DNSValidator type
type DNSValidator struct {
	mock.Mock
}

// IsResolvable provides a mock function with given fields: host
func (_m *DNSValidator) IsResolvable(host string) bool {
	ret := _m.Called(host)

	if len(ret) == 0 {
		panic("no return value specified for IsResolvable")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(host)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// NewDNSValidator creates a new instance of DNSValidator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDNSValidator(t interface {
	mock.TestingT
	Cleanup(func())
}) *DNSValidator {
	mock := &DNSValidator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
