# This rule is not used by the project registry-cache-kubebuilder itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over core.kyma-project.io.kyma-project.io.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: registry-cache-kubebuilder
    app.kubernetes.io/managed-by: kustomize
  name: registrycacheconfig-admin-role
rules:
- apiGroups:
  - core.kyma-project.io.kyma-project.io
  resources:
  - registrycacheconfigs
  verbs:
  - '*'
- apiGroups:
  - core.kyma-project.io.kyma-project.io
  resources:
  - registrycacheconfigs/status
  verbs:
  - get
