apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: registry-cache
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/module: registry-cache
  name: controller-manager
  namespace: system
