namespace: kyma-system
namePrefix: registry-cache-
patches:
- path: manager_webhook_patch.yaml
resources:
- ../crd
- ../rbac
- ../webhook
- metrics_service.yaml
- ../certmanager
- ../manager

sortOptions:
  order: fifo
