name: Lint Markdown Links
run-name: ${{github.event.pull_request.title}}
on: [ pull_request ]
jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: gaurav-nelson/github-action-markdown-link-check@0524e79d8d7d1606112722dd7a3b5f5ce367de3e
        with:
          use-verbose-mode: 'no'
          config-file: '.mlc.config.json'
          folder-path: '.'
          max-depth: -1
